name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Something
      run: mkdir download
    - name: Pull the Docker image
      run: docker pull  docker.io/library/ubuntu:22.04
    - name: save to docker file
      run: docker save -o download/ubuntu2204.docker  docker.io/library/ubuntu:22.04
    - name: Upload archive
      uses: actions/upload-artifact@v3
      with:
        name: download.zip
        path: download/

