name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Something
      run: mkdir download
    - name: Pull the Docker image
      run: docker pull --platform linux/amd64 debian:stable-slim
    - name: save to docker file
      run: docker save -o download/debian-slim.docker debian:stable-slim
    - name: Upload archive
      uses: actions/upload-artifact@v3
      with:
        name: download.zip
        path: download/

